Review H1 2023 changes
aktionariat/contracts pull request #142
Opened 2023-08-08 07:39 UTC by rube-de

2023-08-25 14:20 UTC, mathewmeconry requested changes

2023-08-29 12:28 UTC, rube-de commented on src/multisig/MultiSigWalletMaster.sol
> +    if (Address.isContract(signer) || signer == address(0x0)) {
Our multisig should always have a assumed valid signer, this more like a safe guard beforehand, that you don't add a zero address signer, remove all other signers and lose access. It's debatable as you could set any other random address. As this is not a daily tx I would let it in.

2023-08-29 15:00 UTC, rube-de commented on scripts/migrate_empty_token.js
> +  const recoveryHub = "0xc6AfD3b605957b9BA94143F59d451c657F507516";
that was a one time script to remove a name from a unused contract. deleted the script as it shouldn't be in the main branch.

2023-08-30 06:36 UTC, rube-de commented on deployments/mainnet/InvalidContract.json
> +  "address": "0x27A02627F4D683594984984f0fD2dE9Aa3C8B2f5",
it's an unused contract, was just deployed for name change to "Invalid Contract"

2023-08-30 08:34 UTC, rube-de commented on src/brokerbot/PaymentHub.sol
> +        IERC20(erc20In).approve(address(uniswapRouter), type(uint256).max);
type(uint256).max is > than 2*255, like this the if-block also doesn't get executed in the ERC20Flaggable.
The approval transaction will be slightly more expensive, but for wallet UX it's better to comply with the standard infinity approval like also USDT uses.

2023-09-27 15:59 UTC, rube-de commented on src/brokerbot/PaymentHub.sol
> +            return proceeds - permitInfo.exFee;
fixed with safetransfer

2023-09-28 13:09 UTC, merged